

#wget https://app-polytrack.kodub.com/0.4.2/images/customize.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/back.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/import.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/logo.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/editor.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/settings.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/helmet.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/play.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/discord.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/models/car.glb -P models/

#wget https://app-polytrack.kodub.com/0.4.2/models/block.glb -P models/
#wget https://app-polytrack.kodub.com/0.4.2/models/pillar.glb -P models/
#wget https://app-polytrack.kodub.com/0.4.2/models/plane.glb -P models/
#wget https://app-polytrack.kodub.com/0.4.2/models/road.glb -P models/
#wget https://app-polytrack.kodub.com/0.4.2/models/road_wide.glb -P models/
#wget https://app-polytrack.kodub.com/0.4.2/models/signs.glb -P models/
#wget https://app-polytrack.kodub.com/0.4.2/models/wall_track.glb -P models/

#wget https://app-polytrack.kodub.com/0.4.2/forced_square.json -P ./

#wget https://app-polytrack.kodub.com/0.4.2/tracks/track1.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track2.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track3.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track4.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track5.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track6.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track7.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track8.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track9.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track10.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track11.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track12.track -P tracks/
#wget https://app-polytrack.kodub.com/0.4.2/tracks/track13.track -P tracks/

#wget https://app-polytrack.kodub.com/0.4.2/images/apply.svg -P images/
#get https://app-polytrack.kodub.com/0.4.2/images/arrow_up.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/arrow_right.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/arrow_down.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/arrow_left.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/cancel.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/car_stripe.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/checkpoint.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/clouds.jpg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/copy.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/delete.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/erase.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/export.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/help.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/icon.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/load.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/pause.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/pin.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/preview.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/quit.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/random.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/reset_settings.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/reset.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/rotate.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/save.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/smoke.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/state_invalid.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/state_pending.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/state_verified.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/test.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/verified.svg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/smoke.png -P images/
#wget https://app-polytrack.kodub.com/0.4.2/images/clouds.jpg -P images/
#wget https://app-polytrack.kodub.com/0.4.2/lib/ammo.wasm.js -P lib/
#wget https://app-polytrack.kodub.com/0.4.2/lib/ammo.wasm.wasm -P lib/
#wget https://app-polytrack.kodub.com/0.4.2/audio/music.mp3 -P audio/
#wget https://app-polytrack.kodub.com/0.4.2/audio/checkpoint.flac -P audio/
#wget https://app-polytrack.kodub.com/0.4.2/audio/editor_edit.flac -P audio/
#wget https://app-polytrack.kodub.com/0.4.2/audio/skidding.flac -P audio/
#wget https://app-polytrack.kodub.com/0.4.2/audio/collision.flac -P audio/
#wget https://app-polytrack.kodub.com/0.4.2/audio/tires.flac -P audio/
#wget https://app-polytrack.kodub.com/0.4.2/audio/suspension.flac -P audio/
#wget https://app-polytrack.kodub.com/0.4.2/audio/engine.flac -P audio/
